### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by ludo237** [nuxt-community/tailwindcss-module#319]
### Version
@nuxtjs/tailwindcss: v4.0.2
nuxt: 2.15.3

### Reproduction Link
Currently none but this is the dump of `yarn dev`

```
 ERROR  Failed to compile with 1 errors  
 ERROR  in ./.nuxt/components/nuxt-error.vue?vue&type=style&index=0&lang=css&

Module build failed (from ./node_modules/@nuxt/postcss8/node_modules/postcss-loader/dist/cjs.js):
TypeError: Cannot read property 'map' of undefined
    at \project\path\node_modules\@tailwindcss\jit\src\lib\setupContext.js:708:9
    at \project\path\node_modules\@tailwindcss\jit\src\index.js:37:49
    at LazyResult.runOnRoot (\project\path\node_modules\postcss\lib\lazy-result.js:303:16)
    at LazyResult.runAsync (\project\path\node_modules\postcss\lib\lazy-result.js:355:26)
    at async Object.loader (\project\path\node_modules\@nuxt\postcss8\node_modules\postcss-loa
der\dist\index.js:95:14)
                                                                                           friendly-errors 16:09:35
 @ ./node_modules/thread-loader/dist/cjs.js??ref--3-oneOf-1-0!./node_modules/vue-style-loader??ref--3-oneOf-1-1!./nod
e_modules/@nuxt/postcss8/node_modules/css-loader/dist/cjs.js??ref--3-oneOf-1-2!./node_modules/vue-loader/lib/loaders/
stylePostLoader.js!./node_modules/@nuxt/postcss8/node_modules/postcss-loader/dist/cjs.js??ref--3-oneOf-1-3!./node_mod
ules/vue-loader/lib??vue-loader-options!./.nuxt/components/nuxt-error.vue?vue&type=style&index=0&lang=css& 4:14-380 1
5:3-20:5 16:22-388
 @ ./.nuxt/components/nuxt-error.vue?vue&type=style&index=0&lang=css&
 @ ./.nuxt/components/nuxt-error.vue
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./node_modules/eventsource-polyfill/dist/browserify-eventsource.js (webpack)-hot-middleware/client.js?reload
=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js
```

### Steps to reproduce
Currently none because I don't know if this is a problem caused by me or not

### What is Expected?
Yarn dev build successfully 

### What is actually happening?
Yarn dev does not build successfully

**Comment by Atinux** [comment]
Make sure to `rm -rf node_modules yarn.lock` and `yarn install` again, this can solves weird issues like this one 😅

**Comment by adrianocr** [comment]
This seems to be an issue with postcss-loader and tailwindcss' new jit mode. It is happening for me in react projects too. If I disable `mode: 'jit'` in tailwind.config.js the error goes away.
