### ISSUE TITLE
[JIT] RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by mornir** [nuxt-community/tailwindcss-module#321]
### Version
@nuxtjs/tailwindcss: v4.0.2
nuxt: v2.15.3

### Reproduction Link
https://github.com/mornir/movies-web/tree/dev

### Steps to reproduce
1. `yarn install`
2. `yarn dev`

### What is happening?

When activating JIT, the dev and build process errors out when reading the `tailwind.css` file:
https://github.com/mornir/movies-web/blob/dev/assets/css/tailwind.css

I already tried updating autoprefixer to its latest version, as suggested here:
https://github.com/tailwindlabs/tailwindcss-jit/issues/29

Here's the stack trace:

```bash
 ERROR  Failed to compile with 1 errors


 ERROR  in ./assets/css/tailwind.css

Module build failed (from ./node_modules/@nuxt/postcss8/node_modules/postcss-loader/dist/cjs.js):
RangeError: Maximum call stack size exceeded
    at candidatePermutations (C:\projects\movies-web\node_modules\@tailwindcss\jit\src\lib\generateRules.js:19:32)
    at candidatePermutations.next (<anonymous>)
    at candidatePermutations (C:\projects\movies-web\node_modules\@tailwindcss\jit\src\lib\generateRules.js:41:10)
    at candidatePermutations.next (<anonymous>)
    at candidatePermutations (C:\projects\movies-web\node_modules\@tailwindcss\jit\src\lib\generateRules.js:41:10)
    at candidatePermutations.next (<anonymous>)
    at candidatePermutations (C:\projects\movies-web\node_modules\@tailwindcss\jit\src\lib\generateRules.js:41:10)
    at candidatePermutations.next (<anonymous>)
    at candidatePermutations (C:\projects\movies-web\node_modules\@tailwindcss\jit\src\lib\generateRules.js:41:10)
    at candidatePermutations.next (<anonymous>)
    at candidatePermutations (C:\projects\movies-web\node_modules\@tailwindcss\jit\src\lib\generateRules.js:41:10)
    at candidatePermutations.next (<anonymous>)
    at candidatePermutations (C:\projects\movies-web\node_modules\@tailwindcss\jit\src\lib\generateRules.js:41:10)
    at candidatePermutations.next (<anonymous>)
    at candidatePermutations (C:\projects\movies-web\node_modules\@tailwindcss\jit\src\lib\generateRules.js:41:10)
    at candidatePermutations.next (<anonymous>)

 @ ./assets/css/tailwind.css 4:14-221 15:3-20:5 16:22-229     
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./node_modules/eventsource-polyfill/dist/browserify-eventsource.js (webpack)-hot-middleware/client.js?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js
```

**Comment by mornir** [comment]
So I upgraded all my deps to their latest version and the problem is gone. Not sure what the problem was, but hey it works😃
![image](https://user-images.githubusercontent.com/1411843/113507935-a8168280-954d-11eb-87fd-cfe0d92f99bf.png)
