### ISSUE TITLE
Tailwind CSS IntelliSense not working 

### ISSUE THREAD

**Issue by flyders** [nuxt-community/tailwindcss-module#410]
Auto suggester stop working. Here you are what my output file returns: 

`[Error - 12:43:14 ч.] Tailwind CSS: Can't resolve 'tailwindcss' in 'd:\www\ioio\ioWebApp'
Error
    at new y (c:\Users\FlyderS\.vscode\extensions\bradlc.vscode-tailwindcss-0.7.4\dist\server\tailwindServer.js:56:288476)
    at c:\Users\FlyderS\.vscode\extensions\bradlc.vscode-tailwindcss-0.7.4\dist\server\tailwindServer.js:56:357793
    at Generator.next (<anonymous>)
    at o (c:\Users\FlyderS\.vscode\extensions\bradlc.vscode-tailwindcss-0.7.4\dist\server\tailwindServer.js:56:350663)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)`

**Comment by daan33** [comment]
Do you have a tailwind.config.js file?  You need one for IntelliSense to work.  Try running `npx tailwindcss init`.

**Comment by flyders** [comment]
Yes, I have a tailwind.config.js file.

**Comment by leguian** [comment]
Exactly the same issue here. I have a tailwind.config.js in the right folder as well but I have this output message: 

`[Error - 22:48:09] Tailwind CSS: Can't resolve 'tailwindcss' in 'd:\DevProjects\.git\rightsnow\app-new'
Error
    at new y (c:\Users\legui\.vscode\extensions\bradlc.vscode-tailwindcss-0.7.4\dist\server\tailwindServer.js:56:288476)
    at c:\Users\legui\.vscode\extensions\bradlc.vscode-tailwindcss-0.7.4\dist\server\tailwindServer.js:56:357793
    at Generator.next (<anonymous>)
    at o (c:\Users\legui\.vscode\extensions\bradlc.vscode-tailwindcss-0.7.4\dist\server\tailwindServer.js:56:350663)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)`

**Comment by Phoen1x84** [comment]
I'm having the same issue. I tried renaming `tailwind.config.js` to something else and revert it back to the original which seemed to get the intelliSense working again yesterday but it's stopped working again this morning. Any ideas how to fix?

**Comment by creazy231** [comment]
Should be fixed by their latest update. At least for me 👍🏻

**Comment by zackha** [comment]
If you are working with nuxt3, you can try this.

Add the following configuration to your `.vscode/settings.json file`, so that Tailwind directives have proper autocomplete, syntax highlighting, and linting:

```
"tailwindCSS.experimental.configFile": ".nuxt/tailwind.config.cjs"
"files.associations": {
    "*.css": "tailwindcss"
}
```

detailed: [link](https://tailwindcss.nuxt.dev/tailwind/editor-support)
