### ISSUE TITLE
Nuxt2 fails with @nuxt/tailwindcss 5.3.0: ""

### ISSUE THREAD

**Issue by philipithomas** [nuxt-community/tailwindcss-module#511]
I've been debugging this for awhile and I'm hitting a wall. I'm attempting to upgrade from v4 to v5 of this library to get some tailwind3 features. 

### Version

    "@nuxtjs/tailwindcss": "5.1.3",
    "nuxt": "^2.15.8",

### Reproduction Link

Here's the branch you can clone - it fails to run `yarn run dev`: https://github.com/contraptionco/contraption.co/tree/upgrade-tailwind

### What is Expected?

Succeeding

### What is actually happening?

```
 ERROR  Failed to compile with 1 errors                                  friendly-errors 13:35:21


 ERROR  in ./node_modules/@nuxtjs/tailwindcss/dist/runtime/tailwind.css  friendly-errors 13:35:21

Module build failed (from ./node_modules/@nuxt/postcss8/node_modules/postcss-loader/dist/cjs.js):
Error: Expected a backslash preceding the semicolon.
    at Root._error (/Users/philip/code/contraption.co/node_modules/postcss-selector-parser/dist/parser.js:174:16)
    at Root.error (/Users/philip/code/contraption.co/node_modules/postcss-selector-parser/dist/selectors/root.js:43:19)
    at Parser.error (/Users/philip/code/contraption.co/node_modules/postcss-selector-parser/dist/parser.js:740:21)
    at Parser.missingBackslash (/Users/philip/code/contraption.co/node_modules/postcss-selector-parser/dist/parser.js:744:17)
    at Parser.parse (/Users/philip/code/contraption.co/node_modules/postcss-selector-parser/dist/parser.js:1113:14)
    at Parser.loop (/Users/philip/code/contraption.co/node_modules/postcss-selector-parser/dist/parser.js:1043:12)
    at new Parser (/Users/philip/code/contraption.co/node_modules/postcss-selector-parser/dist/parser.js:164:10)
    at Processor._root (/Users/philip/code/contraption.co/node_modules/postcss-selector-parser/dist/processor.js:53:18)
    at Processor._runSync (/Users/philip/code/contraption.co/node_modules/postcss-selector-parser/dist/processor.js:100:21)
    at Processor.astSync (/Users/philip/code/contraption.co/node_modules/postcss-selector-parser/dist/processor.js:145:17)
    at Object.finalizeSelector (/Users/philip/code/contraption.co/node_modules/tailwindcss/lib/util/formatVariantSelector.js:57:59)
    at /Users/philip/code/contraption.co/node_modules/tailwindcss/lib/lib/generateRules.js:641:65
    at /Users/philip/code/contraption.co/node_modules/postcss/lib/container.js:96:18
    at /Users/philip/code/contraption.co/node_modules/postcss/lib/container.js:55:18
    at Root.each (/Users/philip/code/contraption.co/node_modules/postcss/lib/container.js:41:16)
    at Root.walk (/Users/philip/code/contraption.co/node_modules/postcss/lib/container.js:52:17)
                                                                         friendly-errors 13:35:21
 @ ./node_modules/@nuxtjs/tailwindcss/dist/runtime/tailwind.css 4:14-207 15:3-20:5 16:22-215
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./node_modules/eventsource-polyfill/dist/browserify-eventsource.js (webpack)-hot-middleware/client.js?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js
```

**Comment by Rkallenkoot** [comment]
Getting this issue on pretty much fresh Nuxt 3 + tailwindcss
