### ISSUE TITLE
Error When Adding Default tailwind.config.js from Tailwind Repo

### ISSUE THREAD

**Issue by nicholasfc** [nuxt-community/tailwindcss-module#53]
I'm creating a new nuxt project with nuxt/tailwindcss and everything works fine when the tailwind.config.js file is empty. When I added the provided tailwind.config.js found here https://github.com/tailwindcss/tailwindcss/blob/master/stubs/defaultConfig.stub.js I get 2 errors 
```
 ERROR  Failed to compile with 2 errors


 ERROR  in ./assets/css/tailwind.css

Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: breakpoints is not a function
    at Object.maxWidth (/Users/Nicholas/Coding/my-blog/tailwind.config.js:337:12)
    at Object.keys.reduce (/Users/Nicholas/Coding/my-blog/node_modules/tailwindcss/lib/util/resolveConfig.js:68:65)
    at Array.reduce (<anonymous>)
    at resolveFunctionKeys (/Users/Nicholas/Coding/my-blog/node_modules/tailwindcss/lib/util/resolveConfig.js:66:30)
    at resolveConfig (/Users/Nicholas/Coding/my-blog/node_modules/tailwindcss/lib/util/resolveConfig.js:75:12)
    at /Users/Nicholas/Coding/my-blog/node_modules/tailwindcss/lib/index.js:67:37
    at /Users/Nicholas/Coding/my-blog/node_modules/tailwindcss/lib/processTailwindFeatures.js:32:20
    at LazyResult.run (/Users/Nicholas/Coding/my-blog/node_modules/postcss/lib/lazy-result.js:295:14)
    at LazyResult.asyncTick (/Users/Nicholas/Coding/my-blog/node_modules/postcss/lib/lazy-result.js:208:26)
    at LazyResult.asyncTick (/Users/Nicholas/Coding/my-blog/node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/Users/Nicholas/Coding/my-blog/node_modules/postcss/lib/lazy-result.js:221:14)
    at /Users/Nicholas/Coding/my-blog/node_modules/postcss/lib/lazy-result.js:213:17

 @ ./assets/css/tailwind.css 4:14-166 14:3-18:5 15:22-174
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true&timeout=30000&ansiColors=&overlayStyles=&name=client&path=/__webpack_hmr/client ./.nuxt/client.js


 ERROR  in ./pages/index.vue?vue&type=style&index=0&lang=css&

Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: breakpoints is not a function
    at Object.maxWidth (/Users/Nicholas/Coding/my-blog/tailwind.config.js:337:12)
    at Object.keys.reduce (/Users/Nicholas/Coding/my-blog/node_modules/tailwindcss/lib/util/resolveConfig.js:68:65)
    at Array.reduce (<anonymous>)
    at resolveFunctionKeys (/Users/Nicholas/Coding/my-blog/node_modules/tailwindcss/lib/util/resolveConfig.js:66:30)
    at resolveConfig (/Users/Nicholas/Coding/my-blog/node_modules/tailwindcss/lib/util/resolveConfig.js:75:12)
    at /Users/Nicholas/Coding/my-blog/node_modules/tailwindcss/lib/index.js:67:37
    at /Users/Nicholas/Coding/my-blog/node_modules/tailwindcss/lib/processTailwindFeatures.js:32:20
    at LazyResult.run (/Users/Nicholas/Coding/my-blog/node_modules/postcss/lib/lazy-result.js:295:14)
    at LazyResult.asyncTick (/Users/Nicholas/Coding/my-blog/node_modules/postcss/lib/lazy-result.js:208:26)
    at LazyResult.asyncTick (/Users/Nicholas/Coding/my-blog/node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/Users/Nicholas/Coding/my-blog/node_modules/postcss/lib/lazy-result.js:221:14)
    at /Users/Nicholas/Coding/my-blog/node_modules/postcss/lib/lazy-result.js:213:17
    at process._tickCallback (internal/process/next_tick.js:68:7)

 @ ./node_modules/vue-style-loader??ref--3-oneOf-1-0!./node_modules/css-loader/dist/cjs.js??ref--3-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--3-oneOf-1-2!./node_modules/vue-loader/lib??vue-loader-options!./pages/index.vue?vue&type=style&index=0&lang=css& 4:14-308 14:3-18:5 15:22-316
 @ ./pages/index.vue?vue&type=style&index=0&lang=css&
 @ ./pages/index.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true&timeout=30000&ansiColors=&overlayStyles=&name=client&path=/__webpack_hmr/client ./.nuxt/client.js
```

Not sure if this error is related to the new commit to the file found here https://github.com/tailwindcss/tailwindcss/commit/52a15970898322910cda8c8ff336883eb0cb1355 or if the error is on my end.

Here is my nuxt.config.js file
```
const glob = require("glob");
const path = require("path");
let files = glob.sync("**/*.md", { cwd: "articles" });

export default {
  mode: "universal",
  /*
   ** Headers of the page
   */
  head: {
    title: process.env.npm_package_name || "",
    meta: [
      { charset: "utf-8" },
      { name: "viewport", content: "width=device-width, initial-scale=1" },
      {
        hid: "description",
        name: "description",
        content: process.env.npm_package_description || ""
      }
    ],
    link: [{ rel: "icon", type: "image/x-icon", href: "/favicon.ico" }]
  },
  /*
   ** Customize the progress-bar color
   */
  loading: { color: "#fff" },
  /*
   ** Global CSS
   */
  css: [],
  /*
   ** Plugins to load before mounting the App
   */
  plugins: [],
  /*
   ** Nuxt.js dev-modules
   */
  buildModules: ["@nuxtjs/tailwindcss"],
  /*
   ** Nuxt.js modules
   */
  modules: [],
  /*
   ** Build configuration
   */
  build: {
    extend(config, ctx) {
      config.module.rules.push({
        test: /\.md$/,
        include: path.resolve(__dirname, "content"),
        loader: "frontmatter-markdown-loader"
      });
    },
    generate: {
      routes: function() {
        return files.map(getSlugs);
      }
    }
  }
  /*
   ** You can extend webpack config here
   */
};
```

edit: When I remove the changes from the commit it works just fine. Not sure if the problem is here or on tailwind.

**Comment by Atinux** [comment]
Same issue as #48, fixed in https://github.com/nuxt-community/tailwindcss-module/issues/48#issuecomment-571313874
