### ISSUE TITLE
TypeError: Class constructor extractor cannot be invoked without 'new'

### ISSUE THREAD

**Issue by the94air** [nuxt-community/tailwindcss-module#93]
Hi. I have been running on an error when I run `npm run build`. It seems to be related to the purgecss configuration. I tried using different versions of this package and `nuxt/purgecss` but still no luck on solving this issue. This error shows up when using `webpack` and `postcss` modes.
I am using node `v12.14.0`, npm `v6.13.4` and @nuxt/tailwindcss `v1.4.0`. Here is the error log. Thanks.
```
Hash: 54ea0cc68fd450d62036
Version: webpack 4.42.1
Time: 12551ms
Built at: 04/28/2020 3:18:44 PM
                  Asset       Size  Chunks               Chunk Names
0103730a3815f306edc7.js  170 bytes       1  [immutable]  lang-it
05f466aeca3c1c772fb3.js    186 KiB       3  [immutable]  commons.app
0f34dd4f2fc1ac5d2198.js   11.2 KiB       4  [immutable]  pages/_category/_project
22ef03cfbd57ee3ad812.js  169 bytes       0  [immutable]  lang-en
4d469bed580af0cb4011.js   12.9 KiB       5  [immutable]  pages/_category/index
4eb2f9632c4358ff9add.js   6.83 KiB       6  [immutable]  pages/contattaci
653aace8dd2c024b0012.js   3.76 KiB       7  [immutable]  pages/index
6c376a904afd1d7cb6af.js   2.43 KiB       8  [immutable]  runtime
               LICENSES   1.04 KiB
b9b1f1e49961a8b52dd3.js    101 KiB       2  [immutable]  app
ccbd4db324b5a7fffd6c.js    127 KiB       9  [immutable]  vendors.app
Entrypoint app = 6c376a904afd1d7cb6af.js 05f466aeca3c1c772fb3.js ccbd4db324b5a7fffd6c.js b9b1f1e49961a8b52dd3.js

ERROR in ./.nuxt/components/nuxt-loading.vue?vue&type=style&index=0&lang=css& (./node_modules/extract-css-chunks-webpack-plugin/dist/loader.js??ref--3-oneOf-1-0!./node_modules/css-loader/dist/cjs.js??ref--3-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--3-oneOf-1-2!./node_modules/vue-loader/lib??vue-loader-options!./.nuxt/components/nuxt-loading.vue?vue&type=style&index=0&lang=css&)
Module build failed (from ./node_modules/extract-css-chunks-webpack-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: Class constructor extractor cannot be invoked without 'new'
    at m (/project/node_modules/@fullhuman/postcss-purgecss/node_modules/purgecss/lib/purgecss.js:1:3211)
    at x.extractSelectorsFromFiles (/project/node_modules/@fullhuman/postcss-purgecss/node_modules/purgecss/lib/purgecss.js:1:5234)
    at async /project/node_modules/@fullhuman/postcss-purgecss/lib/postcss-purgecss.js:1:549
    at /project/node_modules/webpack/lib/NormalModule.js:316:20
    at /project/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /project/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/project/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /project/node_modules/postcss-loader/src/index.js:208:9
 @ ./.nuxt/components/nuxt-loading.vue?vue&type=style&index=0&lang=css& 1:0-407 1:423-426 1:428-832 1:428-832
 @ ./.nuxt/components/nuxt-loading.vue
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

ERROR in ./layouts/error.vue?vue&type=style&index=0&id=1ecb33a8&lang=scss&scoped=true& (./node_modules/extract-css-chunks-webpack-plugin/dist/loader.js??ref--7-oneOf-1-0!./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./node_modules/vue-loader/lib??vue-loader-options!./layouts/error.vue?vue&type=style&index=0&id=1ecb33a8&lang=scss&scoped=true&)
Module build failed (from ./node_modules/extract-css-chunks-webpack-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: Class constructor extractor cannot be invoked without 'new'
    at m (/project/node_modules/@fullhuman/postcss-purgecss/node_modules/purgecss/lib/purgecss.js:1:3211)
    at x.extractSelectorsFromFiles (/project/node_modules/@fullhuman/postcss-purgecss/node_modules/purgecss/lib/purgecss.js:1:5234)
    at async /project/node_modules/@fullhuman/postcss-purgecss/lib/postcss-purgecss.js:1:549
    at /project/node_modules/webpack/lib/NormalModule.js:316:20
    at /project/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /project/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/project/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /project/node_modules/postcss-loader/src/index.js:208:9
 @ ./layouts/error.vue?vue&type=style&index=0&id=1ecb33a8&lang=scss&scoped=true& 1:0-468 1:484-487 1:489-954 1:489-954
 @ ./layouts/error.vue
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

ERROR in ./pages/index.vue?vue&type=style&index=0&id=035935ab&lang=scss&scoped=true& (./node_modules/extract-css-chunks-webpack-plugin/dist/loader.js??ref--7-oneOf-1-0!./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./node_modules/vue-loader/lib??vue-loader-options!./pages/index.vue?vue&type=style&index=0&id=035935ab&lang=scss&scoped=true&)
Module build failed (from ./node_modules/extract-css-chunks-webpack-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: Class constructor extractor cannot be invoked without 'new'
    at m (/project/node_modules/@fullhuman/postcss-purgecss/node_modules/purgecss/lib/purgecss.js:1:3211)
    at x.extractSelectorsFromFiles (/project/node_modules/@fullhuman/postcss-purgecss/node_modules/purgecss/lib/purgecss.js:1:5234)
    at async /project/node_modules/@fullhuman/postcss-purgecss/lib/postcss-purgecss.js:1:549
    at /project/node_modules/webpack/lib/NormalModule.js:316:20
    at /project/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /project/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/project/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /project/node_modules/postcss-loader/src/index.js:208:9
 @ ./pages/index.vue?vue&type=style&index=0&id=035935ab&lang=scss&scoped=true& 1:0-468 1:484-487 1:489-954 1:489-954
 @ ./pages/index.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

ERROR in ./pages/contattaci.vue?vue&type=style&index=0&id=83ed0d7a&lang=scss&scoped=true& (./node_modules/extract-css-chunks-webpack-plugin/dist/loader.js??ref--7-oneOf-1-0!./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./node_modules/vue-loader/lib??vue-loader-options!./pages/contattaci.vue?vue&type=style&index=0&id=83ed0d7a&lang=scss&scoped=true&)
Module build failed (from ./node_modules/extract-css-chunks-webpack-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: Class constructor extractor cannot be invoked without 'new'
    at m (/project/node_modules/@fullhuman/postcss-purgecss/node_modules/purgecss/lib/purgecss.js:1:3211)
    at x.extractSelectorsFromFiles (/project/node_modules/@fullhuman/postcss-purgecss/node_modules/purgecss/lib/purgecss.js:1:5234)
    at async /project/node_modules/@fullhuman/postcss-purgecss/lib/postcss-purgecss.js:1:549
    at /project/node_modules/webpack/lib/NormalModule.js:316:20
    at /project/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /project/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/project/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /project/node_modules/postcss-loader/src/index.js:208:9
 @ ./pages/contattaci.vue?vue&type=style&index=0&id=83ed0d7a&lang=scss&scoped=true& 1:0-473 1:489-492 1:494-964 1:494-964
 @ ./pages/contattaci.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

ERROR in ./components/g-video.vue?vue&type=style&index=0&lang=css& (./node_modules/extract-css-chunks-webpack-plugin/dist/loader.js??ref--3-oneOf-1-0!./node_modules/css-loader/dist/cjs.js??ref--3-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--3-oneOf-1-2!./node_modules/vue-loader/lib??vue-loader-options!./components/g-video.vue?vue&type=style&index=0&lang=css&)
Module build failed (from ./node_modules/extract-css-chunks-webpack-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: Class constructor extractor cannot be invoked without 'new'
    at m (/project/node_modules/@fullhuman/postcss-purgecss/node_modules/purgecss/lib/purgecss.js:1:3211)
    at x.extractSelectorsFromFiles (/project/node_modules/@fullhuman/postcss-purgecss/node_modules/purgecss/lib/purgecss.js:1:5234)
    at async /project/node_modules/@fullhuman/postcss-purgecss/lib/postcss-purgecss.js:1:549
    at /project/node_modules/webpack/lib/NormalModule.js:316:20
    at /project/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /project/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/project/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /project/node_modules/postcss-loader/src/index.js:208:9
 @ ./components/g-video.vue?vue&type=style&index=0&lang=css& 1:0-387 1:403-406 1:408-792 1:408-792
 @ ./components/g-video.vue
 @ ./plugins/global-components.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

ERROR in ./components/DoubleImage.vue?vue&type=style&index=0&id=089e1f9a&lang=scss&scoped=true& (./node_modules/extract-css-chunks-webpack-plugin/dist/loader.js??ref--7-oneOf-1-0!./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./node_modules/vue-loader/lib??vue-loader-options!./components/DoubleImage.vue?vue&type=style&index=0&id=089e1f9a&lang=scss&scoped=true&)
Module build failed (from ./node_modules/extract-css-chunks-webpack-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: Class constructor extractor cannot be invoked without 'new'
    at m (/project/node_modules/@fullhuman/postcss-purgecss/node_modules/purgecss/lib/purgecss.js:1:3211)
    at x.extractSelectorsFromFiles (/project/node_modules/@fullhuman/postcss-purgecss/node_modules/purgecss/lib/purgecss.js:1:5234)
    at async /project/node_modules/@fullhuman/postcss-purgecss/lib/postcss-purgecss.js:1:549
    at /project/node_modules/webpack/lib/NormalModule.js:316:20
    at /project/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /project/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/project/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /project/node_modules/postcss-loader/src/index.js:208:9
 @ ./components/DoubleImage.vue?vue&type=style&index=0&id=089e1f9a&lang=scss&scoped=true& 1:0-474 1:490-493 1:495-966 1:495-966
 @ ./components/DoubleImage.vue
 @ ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./pages/_category/index.vue?vue&type=script&lang=js&
 @ ./pages/_category/index.vue?vue&type=script&lang=js&
 @ ./pages/_category/index.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

ERROR in ./components/ProjectNavbar.vue?vue&type=style&index=0&id=24468f48&lang=scss&scoped=true& (./node_modules/extract-css-chunks-webpack-plugin/dist/loader.js??ref--7-oneOf-1-0!./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./node_modules/vue-loader/lib??vue-loader-options!./components/ProjectNavbar.vue?vue&type=style&index=0&id=24468f48&lang=scss&scoped=true&)
Module build failed (from ./node_modules/extract-css-chunks-webpack-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: Class constructor extractor cannot be invoked without 'new'
    at m (/project/node_modules/@fullhuman/postcss-purgecss/node_modules/purgecss/lib/purgecss.js:1:3211)
    at x.extractSelectorsFromFiles (/project/node_modules/@fullhuman/postcss-purgecss/node_modules/purgecss/lib/purgecss.js:1:5234)
    at async /project/node_modules/@fullhuman/postcss-purgecss/lib/postcss-purgecss.js:1:549
    at /project/node_modules/webpack/lib/NormalModule.js:316:20
    at /project/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /project/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/project/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /project/node_modules/postcss-loader/src/index.js:208:9
 @ ./components/ProjectNavbar.vue?vue&type=style&index=0&id=24468f48&lang=scss&scoped=true& 1:0-476 1:492-495 1:497-970 1:497-970
 @ ./components/ProjectNavbar.vue
 @ ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./layouts/single-project.vue?vue&type=script&lang=js&
 @ ./layouts/single-project.vue?vue&type=script&lang=js&
 @ ./layouts/single-project.vue
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

ERROR in ./components/Navbar.vue?vue&type=style&index=0&id=221fe93d&lang=scss&scoped=true& (./node_modules/extract-css-chunks-webpack-plugin/dist/loader.js??ref--7-oneOf-1-0!./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./node_modules/vue-loader/lib??vue-loader-options!./components/Navbar.vue?vue&type=style&index=0&id=221fe93d&lang=scss&scoped=true&)
Module build failed (from ./node_modules/extract-css-chunks-webpack-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: Class constructor extractor cannot be invoked without 'new'
    at m (/project/node_modules/@fullhuman/postcss-purgecss/node_modules/purgecss/lib/purgecss.js:1:3211)
    at x.extractSelectorsFromFiles (/project/node_modules/@fullhuman/postcss-purgecss/node_modules/purgecss/lib/purgecss.js:1:5234)
    at async /project/node_modules/@fullhuman/postcss-purgecss/lib/postcss-purgecss.js:1:549
    at /project/node_modules/webpack/lib/NormalModule.js:316:20
    at /project/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /project/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/project/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /project/node_modules/postcss-loader/src/index.js:208:9
 @ ./components/Navbar.vue?vue&type=style&index=0&id=221fe93d&lang=scss&scoped=true& 1:0-469 1:485-488 1:490-956 1:490-956
 @ ./components/Navbar.vue
 @ ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./layouts/default.vue?vue&type=script&lang=js&
 @ ./layouts/default.vue?vue&type=script&lang=js&
 @ ./layouts/default.vue
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

ERROR in ./assets/css/tailwind.css
Module build failed (from ./node_modules/extract-css-chunks-webpack-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: Class constructor extractor cannot be invoked without 'new'
    at m (/project/node_modules/@fullhuman/postcss-purgecss/node_modules/purgecss/lib/purgecss.js:1:3211)
    at x.extractSelectorsFromFiles (/project/node_modules/@fullhuman/postcss-purgecss/node_modules/purgecss/lib/purgecss.js:1:5234)
    at async /project/node_modules/@fullhuman/postcss-purgecss/lib/postcss-purgecss.js:1:549
    at /project/node_modules/webpack/lib/NormalModule.js:316:20
    at /project/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /project/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/project/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /project/node_modules/postcss-loader/src/index.js:208:9
 @ ./.nuxt/App.js 23:0-36
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

ERROR in ./components/Hamburger.vue?vue&type=style&index=0&id=5d7a56d8&lang=scss&scoped=true& (./node_modules/extract-css-chunks-webpack-plugin/dist/loader.js??ref--7-oneOf-1-0!./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./node_modules/vue-loader/lib??vue-loader-options!./components/Hamburger.vue?vue&type=style&index=0&id=5d7a56d8&lang=scss&scoped=true&)
Module build failed (from ./node_modules/extract-css-chunks-webpack-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: Class constructor extractor cannot be invoked without 'new'
    at m (/project/node_modules/@fullhuman/postcss-purgecss/node_modules/purgecss/lib/purgecss.js:1:3211)
    at x.extractSelectorsFromFiles (/project/node_modules/@fullhuman/postcss-purgecss/node_modules/purgecss/lib/purgecss.js:1:5234)
    at async /project/node_modules/@fullhuman/postcss-purgecss/lib/postcss-purgecss.js:1:549
    at /project/node_modules/webpack/lib/NormalModule.js:316:20
    at /project/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /project/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/project/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /project/node_modules/postcss-loader/src/index.js:208:9
 @ ./components/Hamburger.vue?vue&type=style&index=0&id=5d7a56d8&lang=scss&scoped=true& 1:0-472 1:488-491 1:493-962 1:493-962
 @ ./components/Hamburger.vue
 @ ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./components/ProjectNavbar.vue?vue&type=script&lang=js&
 @ ./components/ProjectNavbar.vue?vue&type=script&lang=js&
 @ ./components/ProjectNavbar.vue
 @ ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./layouts/single-project.vue?vue&type=script&lang=js&
 @ ./layouts/single-project.vue?vue&type=script&lang=js&
 @ ./layouts/single-project.vue
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

ERROR in ./components/InnerNavbar.vue?vue&type=style&index=0&id=3d57b2a5&lang=scss&scoped=true& (./node_modules/extract-css-chunks-webpack-plugin/dist/loader.js??ref--7-oneOf-1-0!./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./node_modules/vue-loader/lib??vue-loader-options!./components/InnerNavbar.vue?vue&type=style&index=0&id=3d57b2a5&lang=scss&scoped=true&)
Module build failed (from ./node_modules/extract-css-chunks-webpack-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: Class constructor extractor cannot be invoked without 'new'
    at m (/project/node_modules/@fullhuman/postcss-purgecss/node_modules/purgecss/lib/purgecss.js:1:3211)
    at x.extractSelectorsFromFiles (/project/node_modules/@fullhuman/postcss-purgecss/node_modules/purgecss/lib/purgecss.js:1:5234)
    at async /project/node_modules/@fullhuman/postcss-purgecss/lib/postcss-purgecss.js:1:549
    at /project/node_modules/webpack/lib/NormalModule.js:316:20
    at /project/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /project/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/project/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /project/node_modules/postcss-loader/src/index.js:208:9
 @ ./components/InnerNavbar.vue?vue&type=style&index=0&id=3d57b2a5&lang=scss&scoped=true& 1:0-474 1:490-493 1:495-966 1:495-966
 @ ./components/InnerNavbar.vue
 @ ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./components/Navbar.vue?vue&type=script&lang=js&
 @ ./components/Navbar.vue?vue&type=script&lang=js&
 @ ./components/Navbar.vue
 @ ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./layouts/default.vue?vue&type=script&lang=js&
 @ ./layouts/default.vue?vue&type=script&lang=js&
 @ ./layouts/default.vue
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

ERROR in ./assets/sass/app.scss
Module build failed (from ./node_modules/extract-css-chunks-webpack-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: Class constructor extractor cannot be invoked without 'new'
    at m (/project/node_modules/@fullhuman/postcss-purgecss/node_modules/purgecss/lib/purgecss.js:1:3211)
    at x.extractSelectorsFromFiles (/project/node_modules/@fullhuman/postcss-purgecss/node_modules/purgecss/lib/purgecss.js:1:5234)
    at async /project/node_modules/@fullhuman/postcss-purgecss/lib/postcss-purgecss.js:1:549
    at /project/node_modules/webpack/lib/NormalModule.js:316:20
    at /project/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /project/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/project/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /project/node_modules/postcss-loader/src/index.js:208:9
 @ ./.nuxt/App.js 24:0-33
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

 FATAL  Nuxt build error                                                                                                                                                    15:18:44

  at WebpackBundler.webpackCompile (node_modules/@nuxt/webpack/dist/webpack.js:5351:21)
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
  at async WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:5300:5)
  at async Builder.build (node_modules/@nuxt/builder/dist/builder.js:5602:5)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-build.js:104:7)
  at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:2759:7)

```

**Comment by delineas** [comment]
Hi. Same issue here

In my case: `node 10.0.0` 

Thanks

**Comment by Atinux** [comment]
I don't recommend to use `webpack` mode for purge as well as `extractCSS`, a reproduction will help to look at this issue.

See the codesandbox: https://codesandbox.io/s/o4vn5pvp7q

**Comment by the94air** [comment]
It seems that this issue has fixed itself in our case and I am not able to reproduce it anymore. Although the build is successful in both "postcss" and "webpack" modes currently. I will leave the issue open for @delineas if he is willing to continue investigating on it. Thanks for help @Atinux :)

**Comment by delineas** [comment]
Same for me. You can close it, thanks :)

**Comment by Ondolin** [comment]
Hi! I still got the problem. Any news on that?

**Comment by MUMUKSHMEGHWAL** [comment]
@Ondolin Please refer to https://github.com/Developmint/nuxt-purgecss/issues/89#issuecomment-686339407

**Comment by besrabasant** [comment]
I am still facing the issue.
